version: '3.4'

services:
  eureka-server:
    build:
      context: demo
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  configserver:
    build:
      context: config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      WAITFORIT_HOST: eureka-server
      WAITFORIT_PORT: 8761
      WAITFORIT_TIMEOUT: 60
    depends_on:
      - eureka-server

  postgres:
    image: postgres
    restart: always
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: countryDb
      PGPORT: 5434
    volumes:
      - /docker-volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "8081-8082:8081"
    environment:
      WAITFORIT_HOST: configserver
      WAITFORIT_PORT: 8888
      WAITFORIT_TIMEOUT: 120
    depends_on:
      - eureka-server
      - postgres
      - configserver

  getaway:
    build:
      context: getaway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      WAITFORIT_HOST: configserver
      WAITFORIT_PORT: 8888
      WAITFORIT_TIMEOUT: 120
    depends_on:
      - eureka-server
      - client
      - configserver

  rabbit:
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
    - "9080:9080"
  
  grafana:
    image: grafana/grafana
    network_mode: host
    ports:
    - "3000:3000"
    