### Fetch entities
GET http://localhost:8080/getaway/countries
Content-type: application/json

### Fetch entity by id
GET http://localhost:8080/getaway/countries/1
Content-type: application/json

### Create entity
POST http://localhost:8080/getaway/countries/create
Content-Type: application/json

{
	"name": "China",
	"currency": "UCHY",
	"languages": ["china", "ukrainian"],
	"capital": "Pekin",
	"population": "1500000000",
	"phonePrefix": "+86",
	"budget": 100000,
	"gdp": 29
}

### Update entity
PUT http://localhost:8080/getaway/countries/update
Content-Type: application/json

{
  "id": 1,
	"name": "HJK",
	"currency": "UCHF",
	"languages": ["china", "ukrainian"],
	"capital": "Pekin",
	"population": "1500000000",
	"phonePrefix": "+86",
	"budget": 100000,
	"gdp": 29
}

### Delete entity
DELETE http://localhost:8080/getaway/countries/delete/1
Content-Type: application/json
