### Api-gateway config
GET http://localhost:8080/configs
Content-type: application/json

### Service (instance 1) config
GET http://localhost:8081/configs
Content-type: application/json

### Service (instance 2) config
GET http://localhost:8082/configs
Content-type: application/json

### Configs in config server
GET http://localhost:8888/countries-service/default
Content-type: application/json

### Config refresh
POST http://localhost:8081/actuator/refresh

### Bus refresh
POST http://localhost:8081/actuator/bus-refresh
